package com.uber.tchannel.tracing;

import com.google.common.base.Function;
import com.google.common.base.Predicate;
import com.google.common.collect.Iterators;
import com.google.common.collect.Maps;
import io.opentracing.propagation.TextMap;

import java.util.Iterator;
import java.util.Map;

class PrefixedHeadersCarrier implements TextMap {
    /**
     * Prefix used with all keys generated by the tracer when marshalling SpanContext
     * to a map of headers.
     * <p>
     * This string value is shared across all implementations of TChannel.
     */
    private static final String TRACING_KEY_PREFIX = "$tracing$";

    private static final Function<String, String> PREFIXED_KEYS = prefixedKeys(TRACING_KEY_PREFIX);

    private static final Function<String, String> UNPREFIXED_KEYS = unprefixedKeys(TRACING_KEY_PREFIX);

    private final Map<String, String> headers;
    private final String prefix;
    private final Function<String, String> encoder;
    private final Function<String, String> decoder;

    PrefixedHeadersCarrier(Map<String, String> headers) {
        this(headers, TRACING_KEY_PREFIX, PREFIXED_KEYS, UNPREFIXED_KEYS);
    }

    PrefixedHeadersCarrier(Map<String, String> headers, String prefix) {
        this(headers, prefix, prefixedKeys(prefix), unprefixedKeys(prefix));
    }

    private PrefixedHeadersCarrier(
            Map<String, String> headers,
            String prefix,
            Function<String, String> encoder,
            Function<String, String> decoder
    ) {
        this.headers = headers;
        this.prefix = prefix;
        this.encoder = encoder;
        this.decoder = decoder;
    }

    @Override
    public Iterator<Map.Entry<String, String>> iterator() {
        return Iterators.transform(Iterators.filter(headers.entrySet().iterator(),
                new Predicate<Map.Entry<String, String>>() {
                    @Override
                    public boolean apply(Map.Entry<String, String> entry) {
                        return entry.getKey().startsWith(prefix);
                    }
                }),
                new Function<Map.Entry<String, String>, Map.Entry<String, String>>() {
                    @Override
                    public Map.Entry<String, String> apply(Map.Entry<String, String> entry) {
                        return Maps.immutableEntry(
                                decoder.apply(entry.getKey()),
                                entry.getValue());
                    }
                });
    }

    @Override
    public void put(String key, String value) {
        headers.put(encoder.apply(key), value);
    }

    Map<String, String> getNonTracingHeaders() {
        return Maps.filterKeys(headers, new Predicate<String>() {
            @Override
            public boolean apply(String key) {
                return !key.startsWith(prefix);
            }
        });
    }

    private static CachedKeyTransformer prefixedKeys(final String prefix) {
        return new CachedKeyTransformer(new Function<String, String>() {
            @Override
            public String apply(String key) {
                return prefix + key;
            }
        });
    }


    private static CachedKeyTransformer unprefixedKeys(final String prefix) {
        return new CachedKeyTransformer(new Function<String, String>() {
            @Override
            public String apply(String key) {
                return key.substring(prefix.length());
            }
        });
    }

}
